# Latent Semantic Analysis

Latent Semantic Analysis (LSA), a high-dimensional linear associative model that embodies no human knowledge beyond its general learning mechanism , to analyze a large corpus of natural text and generate a representation that captures the similarity of words and text passages.

From: *Landauer, Thomas & Dumais Susan (1997).* A solution to Plato's problem: The latent semantic analysis theory of acquisition, induction, and representation of knowledge.

## Initialization
Setting up an example 'bag of words' DataFrame. The real data would come from analysing the word occurences in different text samples, or 'contexts'.  

In [19]:
import numpy as np
import pandas as pd
np.set_printoptions(suppress=True, precision=4)

words = np.array([
    [1,1,1,0,0],
    [3,3,3,0,0],
    [4,4,4,0,0],
    [5,5,5,0,0],
    [0,2,0,4,4],
    [0,0,0,5,5],
    [0,1,0,2,2]])

idx = ['word'+str(i) for i in range(1,8)]
col = ['context'+str(i) for i in range(1,6)]
A = pd.DataFrame(data=words, index=idx, columns=col)

### Example Data
The example 'bag of words' now looks like this:

In [20]:
print(A)

       context1  context2  context3  context4  context5
word1         1         1         1         0         0
word2         3         3         3         0         0
word3         4         4         4         0         0
word4         5         5         5         0         0
word5         0         2         0         4         4
word6         0         0         0         5         5
word7         0         1         0         2         2


## Singular Value Decomposition

At the heart of the LSA is a dimensionality reduction technique called: **Singular Value Decomposition (SVD)**

Perfoming the SVD on the example matrix using the numpy.svd() method:

In [21]:
U, E, V = np.linalg.svd(A.values, full_matrices=False)

This will return the following matrices:

In [22]:
print(U, E, V, sep=2*'\n')

[[-0.1376 -0.0236 -0.0108  0.5601 -0.3757]
 [-0.4128 -0.0708 -0.0324  0.2064  0.756 ]
 [-0.5504 -0.0944 -0.0432 -0.7248 -0.1846]
 [-0.688  -0.1181 -0.054   0.344  -0.2308]
 [-0.1528  0.5911  0.6537  0.      0.2   ]
 [-0.0722  0.7313 -0.6782  0.      0.    ]
 [-0.0764  0.2956  0.3268  0.     -0.4   ]]

[ 12.481    9.5086   1.3456   0.       0.    ]

[[-0.5623 -0.5929 -0.5623 -0.0901 -0.0901]
 [-0.1266  0.0288 -0.1266  0.6954  0.6954]
 [-0.4097  0.8048 -0.4097 -0.0913 -0.0913]
 [-0.7071  0.      0.7071  0.      0.    ]
 [ 0.     -0.      0.     -0.7071  0.7071]]


## Dimensionality Reduction

Now doing some kick-ass dimensionality reduction by removing the weakest 'concept' in the singular value matrix 'E':

In [23]:
E[2] = 0.0

print(E)

[ 12.481    9.5086   0.       0.       0.    ]


We can now reconstruct the original matrix A with the reduced matrix E.


In [24]:
A2 = np.dot(np.dot(U, np.diag(E)), V)

print(A2)

[[ 0.994   1.0117  0.994  -0.0013 -0.0013]
 [ 2.9821  3.0351  2.9821 -0.004  -0.004 ]
 [ 3.9762  4.0468  3.9762 -0.0053 -0.0053]
 [ 4.9702  5.0585  4.9702 -0.0066 -0.0066]
 [ 0.3603  1.2922  0.3603  4.0803  4.0803]
 [-0.3739  0.7344 -0.3739  4.9167  4.9167]
 [ 0.1802  0.6461  0.1802  2.0401  2.0401]]


## Cosine Similarity

The vectors in the new matrix A2 can now be compared using the cosine similarity.

$$cos(\pmb x, \pmb y) = \frac {\pmb x \cdot \pmb y}{||\pmb x|| \cdot ||\pmb y||}$$


In [35]:
import math

def cosine_similarity(a, b):
    return sum([i*j for i,j in zip(a, b)])/(math.sqrt(sum([i*i for i in a]))* math.sqrt(sum([i*i for i in b])))

print(A2[4], A2[5], sep='\n')
print(cosine_similarity(A2[4], A2[5]))

[ 0.3603  1.2922  0.3603  4.0803  4.0803]
[-0.3739  0.7344 -0.3739  4.9167  4.9167]
0.980428708498


In [36]:
print(A2[0], A2[5], sep='\n')
print(cosine_similarity(A2[0], A2[5]))

[ 0.994   1.0117  0.994  -0.0013 -0.0013]
[-0.3739  0.7344 -0.3739  4.9167  4.9167]
-0.0010928254832
